version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
  # reduce frequent email update
      interval: "monthly"
  - package-ecosystem: npm
    directory: "/"
    schedule:
     # reduce frequent email update
      interval: "monthly"
#     schedule:
#       interval: "daily"
#       time: "21:00"
    open-pull-requests-limit: 10
    # Increase the version requirements
    # only when required
    versioning-strategy: increase-if-necessary
    #reviewers:
    #  - "souyang"
    #assignees:
    #  - "souyang"
    labels:
      - "dependencies"
      - "npm"
